changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Operations and documentation
      labels: [operations, documentation, maintenance, dependencies]
    - title: Other changes
      labels: ["*"]
